# baseURL: "https://cjlmonster.github.io/"
baseURL: "https://www.cjlmonster.cn/"
defaultcontentlanguage: "zh-cn"
languageCode: "zh-cn"
title: "Hyou"

theme: "mdui"

themeDir: "./themes"

paginate: 5  # 分页

disqusShortname: "cjlmonster"

Menus:
  main:
    - Name: "主页"
      Pre: "home"
      URL: "/"
      Weight: 1
    - Name: "分类"
      Pre: "local_library"
      URL: "/sections"
      Weight: 2
    - Name: "标签"
      Pre: "local_offer"
      URL: "/tags"
      Weight: 3
    - Name: "关于"
      Pre: "brightness_auto"
      URL: "/about"
      Weight: 4

taxonomies:
  tag: "tags"
  # category: "categories"
  # topic: "topics"

params:
  themePrimary: "teal"
  themeAccent: "deep-orange"
  themeLayout: "auto" # light, dark And auto
  description: "An Simlpe Blog"
  # 个人信息
  niconame: "Rei"
  email: "cjlmonster@163.com"
  signature: "白开水与方便面"
  headUrl: "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic1.win4000.com%2Fpic%2Fd%2F65%2Fb71b1394172.jpg&refer=http%3A%2F%2Fpic1.win4000.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1625107381&t=0ea60414bcd40f5f3e421eae7e483883"
