baseURL: "http://example.org/"
defaultcontentlanguage: "zh-cn"
languageCode: "zh-cn"
title: "Hyouka"

theme: "mdui"

themeDir: "./themes"

Menus:
  main:
    - Name: "首页"
      Pre: "home"
      URL: "/"
      Weight: 1
    - Name: "归档"
      Pre: "bookmark"
      URL: "/categories"
      Weight: 2
    - Name: "标签"
      Pre: "loyalty"
      URL: "/tags"
      Weight: 3
    - Name: "关于我"
      Pre: "brightness_auto"
      URL: "/about"
      Weight: 4

taxonomies:
  tag: "tags"
  category: "categories"
  # topic: "topics"

params:
  description: "An Simlpe Blog"
  themeColor: "theme-base-0d"
  layoutReverse: false
  disqusShortname: "cjlmonster"
