baseURL: "https://cjlmonster.github.io/"
defaultcontentlanguage: "zh-cn"
languageCode: "zh-cn"
title: "Cjlmonster"

theme: "mdui"

themeDir: "./themes"

paginate: 5  # 分页

disqusShortname: "cjlmonster"

Menus:
  main:
    - Name: "主页"
      Pre: "home"
      URL: "/"
      Weight: 1
    - Name: "博客专栏"
      Pre: "local_library"
      URL: "/sections"
      Weight: 2
    - Name: "标签"
      Pre: "local_offer"
      URL: "/tags"
      Weight: 3
    - Name: "关于我"
      Pre: "brightness_auto"
      URL: "/about"
      Weight: 4

taxonomies:
  tag: "tags"
  # category: "categories"
  # topic: "topics"

params:
  themePrimary: "teal"
  themeAccent: "deep-orange"
  themeLayout: "auto" # light, dark And auto
  description: "An Simlpe Blog"
