# baseURL: "https://cjlmonster.github.io/"
baseURL: "https://www.cjlmonster.cn/"
defaultcontentlanguage: "zh-cn"
languageCode: "zh-cn"
title: "Hyou"

theme: "mdui"

themeDir: "./themes"

paginate: 5  # 分页

disqusShortname: "cjlmonster"

Menus:
  main:
    - Name: "主页"
      Pre: "home"
      URL: "/"
      Weight: 1
    - Name: "博客专栏"
      Pre: "local_library"
      URL: "/sections"
      Weight: 2
    - Name: "标签"
      Pre: "local_offer"
      URL: "/tags"
      Weight: 3
    - Name: "关于我"
      Pre: "brightness_auto"
      URL: "/about"
      Weight: 4

taxonomies:
  tag: "tags"
  # category: "categories"
  # topic: "topics"

params:
  themePrimary: "teal"
  themeAccent: "deep-orange"
  themeLayout: "auto" # light, dark And auto
  description: "An Simlpe Blog"
  # 个人信息
  niconame: "Rei"
  email: "cjlmonster@163.com"
  signature: "白开水与方便面"
  headUrl: "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fc-ssl.duitang.com%2Fuploads%2Fitem%2F201909%2F27%2F20190927153637_jtitf.thumb.700_0.jpeg&refer=http%3A%2F%2Fc-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1622186371&t=688a32974f766c36aac39793b994b0fb"
